# Generated by Django 3.1.6 on 2021-03-07 23:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_auto_20210307_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health',
            name='created_at',
        ),
        migrations.AddField(
            model_name='health',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
