# Generated by Django 3.1.6 on 2021-03-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_well_being_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='amount_of_posts_linked',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
