# Generated by Django 3.1.6 on 2021-03-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20210303_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('friend', 'Friend request'), ('react', 'React'), ('comment', 'Comment'), ('message', 'Message'), ('mention', 'Mention')], max_length=20),
        ),
    ]
