# Generated by Django 3.1.6 on 2021-03-03 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20210223_1536'),
        ('notification', '0003_auto_20210303_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='feed.post'),
        ),
    ]
