# Generated by Django 3.1.6 on 2021-02-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20210223_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='vote',
            new_name='post',
        ),
    ]
