# Generated by Django 3.1.6 on 2021-02-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20210223_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbs_down',
            new_name='down_votes',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='thumbs_up',
            new_name='up_votes',
        ),
    ]
