# Generated by Django 3.1.6 on 2021-02-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20210223_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='vote_type',
            new_name='type',
        ),
    ]
