# Generated by Django 3.1.6 on 2021-02-23 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_report'),
        ('feed', '0006_auto_20210223_1416'),
        ('feed', '0002_comment'),
    ]

    operations = [
    ]
