# Generated by Django 3.1.6 on 2021-03-04 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_topic_created_at'),
        ('feed', '0009_posttag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='posttag',
            unique_together={('post', 'topic')},
        ),
    ]
