# Generated by Django 3.1.6 on 2021-03-06 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_auto_20210306_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='body',
        ),
    ]
